version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn integration
      - run: yarn compile
      - run: yarn build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build